### ISSUE TITLE
mira3 wrapper is missing license & acknowlegdements

### ISSUE THREAD

**Issue by peterjc** [jvolkening/galaxy-tools#1]
Hello Jeremy,

Regarding your MIRA3 wrapper for Galaxy, in this repository:

https://toolshed.g2.bx.psu.edu/view/jvolkening/mira3/
https://github.com/jvolkening/galaxy-tools/tree/master/tools/mira3

It Is clearly derived from my wrapper:

https://toolshed.g2.bx.psu.edu/view/peterjc/mira_assembler/
https://github.com/peterjc/galaxy_mira/tree/master/tools/mira3

However, you are not following the terms of the MIT license by omitting the licence and copyright statement. Furthermore, you have removed my citation request from the XML file.

I would expect you to at least address these points, but a better outcome would be to look at incorporating your improvements into the original. The main change I noticed is the removal of the Python wrapper script and handling the output files directly with Galaxy ``from_work_dir`` feature.

**Comment by jvolkening** [comment]
Peter,

My apologies. Please trust that I didn't mean to intentionally omit any appropriate acknowledgements or abuse the license -- it was a simple oversight. It has been a number of years since I forked your wrapper for use on a private Galaxy instance, and it has been privately used and modified since then. I only uploaded it to the main toolshed yesterday (under mild protest) at the request of a collaborator who needs to install it on a separate Galaxy instance which only accepts mainline tools. I will fix the license and acknowledgements later today.

> a better outcome would be to look at incorporating your improvements into the original. The main change I noticed is the removal of the Python wrapper script and handling the output files directly with Galaxy from_work_dir feature.

Actually, the primary difference (at least, the reason for the original fork) was the addition of sanitized free-form text input parameters which allow the user to modify arbitrary MIRA parameters. Some of them are important to our work, and your original wrapper did not allow for much configuration beyond the basics (de novo vs mapping, draft vs accurate, etc). It was much easier to allow free-form specification than to try to wrap all (hundreds??) of parameters available with MIRA. Of course, even with sanitization it is less robust to user error.

If you are amenable to incorporating these changes into your own MIRA3 repo, I agree that this is a better long term solution and am happy to put together a PR.

**Comment by peterjc** [comment]
That's much clearer, thank you. And thank you for opening the pull request https://github.com/peterjc/galaxy_mira/pull/4
